# PORFAVOR NO BORRAR ESTO:
# EJECUTAR PRIMERO EL SIGUIENTE COMANDO PARA CREAR LA RED DE DOCKER:
# docker network create --driver bridge uqcloud

services:
  #servicio del servidor de procesamiento
  procesamiento:
    build: ./servidor_procesamiento
    ports:
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - general
      - uqcloud
    environment:
      - DATABASE=database 
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=root
      - DB_NAME=uqcloud
    depends_on:
      - database

  #servicio del servidor web
  web:
    build: ./servidor_web
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - general
    environment:
      - servidor_procesamiento=procesamiento
    depends_on:
      - procesamiento

  #servicio de la base de datos
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    expose:
      - "3307"
    networks:
      - general
    volumes:
    - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: uqcloud
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_TIME_ZONE: 'America/Bogota'

volumes:
  mysql-data:      

networks:
  uqcloud:
    external: true  
  general:                                       
