services:
  #servicio del servidor de procesamiento
  procesamiento:
    build: ./servidor_procesamiento
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - DATABASE=database 
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=root
      - DB_NAME=uqcloud
    depends_on:
      - database

  #servicio del servidor web
  web:
    build: ./servidor_web
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - servidor_procesamiento = procesamiento
    depends_on:
      - procesamiento

  #servicio de la base de datos
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
    - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: uqcloud
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_TIME_ZONE: 'America/Bogota'

volumes:
  mysql-data:                                               
