# PORFAVOR NO BORRAR ESTO:
# EJECUTAR PRIMERO EL SIGUIENTE COMANDO PARA CREAR LA RED DE DOCKER:
# docker network create uqcloud

services:
  #servicio del servidor de procesamiento
  procesamiento:
    build: ./servidor_procesamiento
    ports:
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - general
      - uqcloud
    environment:
      - DATABASE=database 
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=root
      - DB_NAME=uqcloud
    depends_on:
      - database

  #servicio del servidor web
  web:
    build: ./servidor_web
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - general
    environment:
      - servidor_procesamiento=procesamiento
    depends_on:
      - procesamiento

  #servicio de la base de datos
  database:
    image: mysql:5.7
    ports:
      - "3307:3306"
    expose:
      - "3307"
    networks:
      - general
    volumes:
    - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: uqcloud
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_TIME_ZONE: 'America/Bogota'
  
  # Servicio de Prometheus para monitoreo
  prometheus:
    image: docker.io/prom/prometheus:v2.54.1
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    volumes:
      - ./metrics_config/prometheus.yml:/etc/prometheus/prometheus.yml:wr 
      - prometheus-data:/prometheus
    networks:
      - general
      - uqcloud
    restart: unless-stopped
  
  # Servicio del actualizador de configuración de Prometheus
  prometheus-config:
    build: ./metrics_config
    volumes:
      - ./metrics_config/prometheus.yml:/etc/prometheus/prometheus.yml:wr  # Compartir archivo con Prometheus
      - ./metrics_config/update_prometheus_config.sh:/etc/prometheus/update_prometheus_config.sh:x
    depends_on:
      - procesamiento
    networks:
      - general
      - uqcloud

  # Servicio de Grafana para visualización de métricas
  grafana:
    image: docker.io/grafana/grafana-oss:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true  # Permitir embebidos
    volumes:
      - grafana-data:/var/lib/grafana
      - ./metrics_config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./metrics_config/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    restart: unless-stopped
    networks:
      - general
      - uqcloud

volumes:
  mysql-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local  

networks:
  uqcloud:
    external: true  
  general:                                       
