{
 "title": "Usage Statistics Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "# Hosts Registrados",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT COUNT(id) FROM uqcloud.host LIMIT 50 "
    }
   ]
  },
  {
   "title": "# Hosts Utilizados",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT DISTINCT h.id AS \"Host Id\", COUNT(h.id) AS \"# VMs\"\r\nFROM uqcloud.host AS h\r\nJOIN uqcloud.maquina_virtual AS vm ON h.id = vm.host_id\r\nGROUP BY h.id\r\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Cantidad Total de VMs Creadas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT COUNT(id) FROM uqcloud.maquina_virtual LIMIT 50 "
    }
   ]
  },
  {
   "title": "Cantidad de VMs Encendidas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT COUNT(id) FROM uqcloud.maquina_virtual WHERE estado = 'Encendido' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Cantidad de VMs Apagadas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT COUNT(id) FROM uqcloud.maquina_virtual WHERE estado = 'Apagado' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Promedio de VMs Creadas Por Host",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT \r\n    AVG(maquinas_por_host) AS promedio_maquinas_virtuales\r\nFROM (\r\n    SELECT \r\n        h.id AS host_id,\r\n        COUNT(mv.id) AS maquinas_por_host\r\n    FROM \r\n        host h\r\n    LEFT JOIN \r\n        maquina_virtual mv ON h.id = mv.host_id\r\n    GROUP BY \r\n        h.id\r\n) AS subquery;"
    }
   ]
  },
  {
   "title": "Cantidad de VMs Procesando",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT COUNT(id) FROM uqcloud.maquina_virtual WHERE estado = 'Procesando' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Cantidad de VMs Eliminadas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT COUNT(id) FROM uqcloud.maquina_virtual WHERE deleted_at IS NOT NULL LIMIT 50 "
    }
   ]
  },
  {
   "title": "Cantidad de VMs por Uso de RAM",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT \r\n    mv.ram AS ram_usada, COUNT(*) as cantidad_vms\r\nFROM \r\n    maquina_virtual mv\r\nGROUP BY mv.ram\r\nORDER BY cantidad_vms DESC;\r\n"
    }
   ]
  },
  {
   "title": "Uso Promedio de CPU Seleccionado para las VMs",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 7 },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT \r\n    mv.cpu AS cpu_usado, COUNT(*) AS cantidad_vms\r\nFROM \r\n    maquina_virtual mv\r\nGROUP BY mv.cpu\r\nORDER BY cantidad_vms DESC;\r\n\r\n    \r\n"
    }
   ]
  },
  {
   "title": "Distribuciones S.O Utilizadas",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT \r\n    mv.distribucion_sistema_operativo AS distribucion_sistema_operativo,\r\n    COUNT(*) AS cantidad\r\nFROM \r\n    maquina_virtual mv\r\nGROUP BY \r\n    mv.distribucion_sistema_operativo\r\nORDER BY \r\n    cantidad DESC;"
    }
   ]
  },
  {
   "title": "Cantidad de VMs Creadas por Hora",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT \r\n    HOUR(fecha_creacion) AS hora,\r\n    COUNT(*) AS cantidad_mvs\r\nFROM \r\n    maquina_virtual\r\nWHERE \r\n    HOUR(fecha_creacion) BETWEEN 7 AND 21\r\nGROUP BY \r\n    HOUR(fecha_creacion)\r\nORDER BY \r\n    hora;"
    }
   ]
  },
  {
   "title": "# Personas Registradas en Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT COUNT(*)\r\nFROM uqcloud.persona AS p\r\nWHERE p.rol!=1;"
    }
   ]
  },
  {
   "title": "# Personas Registradas y Activas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 5, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT COUNT(*)\r\nFROM uqcloud.persona AS p\r\nWHERE p.rol!=1;"
    }
   ]
  },
  {
   "title": "# Personas Registradas Hoy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT COUNT(*)\r\nFROM uqcloud.persona AS p\r\nWHERE p.rol != 1 \r\nAND DATE(p.created_at) = CURDATE();"
    }
   ]
  },
  {
   "title": "# Personas Registradas Este Mes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uqcloud",
     "rawSql": "SELECT COUNT(*)\r\nFROM uqcloud.persona AS p\r\nWHERE p.rol != 1 \r\nAND YEARWEEK(p.created_at, 1) = YEARWEEK(CURDATE(), 1);"
    }
   ]
  }
 ]
}